insert into aisle values (1,"prepared soups salads");
insert into aisle values (2,"specialty cheeses");
insert into aisle values (3,"energy granola bars");
insert into aisle values (4,"instant foods");
insert into aisle values (5,"marinades meat preparation");
insert into aisle values (6,"other");
insert into aisle values (7,"packaged meat");
insert into aisle values (8,"bakery desserts");
insert into aisle values (9,"pasta sauce");
insert into aisle values (10,"kitchen supplies");
insert into aisle values (11,"cold flu allergy");
insert into aisle values (12,"fresh pasta");
insert into aisle values (13,"prepared meals");
insert into aisle values (14,"tofu meat alternatives");
insert into aisle values (15,"packaged seafood");
insert into aisle values (16,"fresh herbs");
insert into aisle values (17,"baking ingredients");
insert into aisle values (18,"bulk dried fruits vegetables");
insert into aisle values (19,"oils vinegars");
insert into aisle values (20,"oral hygiene");
insert into aisle values (21,"packaged cheese");
insert into aisle values (22,"hair care");
insert into aisle values (23,"popcorn jerky");
insert into aisle values (24,"fresh fruits");
insert into aisle values (25,"soap");
insert into aisle values (26,"coffee");
insert into aisle values (27,"beers coolers");
insert into aisle values (28,"red wines");
insert into aisle values (29,"honeys syrups nectars");
insert into aisle values (30,"latino foods");
insert into aisle values (31,"refrigerated");
insert into aisle values (32,"packaged produce");
insert into aisle values (33,"kosher foods");
insert into aisle values (34,"frozen meat seafood");
insert into aisle values (35,"poultry counter");
insert into aisle values (36,"butter");
insert into aisle values (37,"ice cream ice");
insert into aisle values (38,"frozen meals");
insert into aisle values (39,"seafood counter");
insert into aisle values (40,"dog food care");
insert into aisle values (41,"cat food care");
insert into aisle values (42,"frozen vegan vegetarian");
insert into aisle values (43,"buns rolls");
insert into aisle values (44,"eye ear care");
insert into aisle values (45,"candy chocolate");
insert into aisle values (46,"mint gum");
insert into aisle values (47,"vitamins supplements");
insert into aisle values (48,"breakfast bars pastries");
insert into aisle values (49,"packaged poultry");
insert into aisle values (50,"fruit vegetable snacks");
insert into aisle values (51,"preserved dips spreads");
insert into aisle values (52,"frozen breakfast");
insert into aisle values (53,"cream");
insert into aisle values (54,"paper goods");
insert into aisle values (55,"shave needs");
insert into aisle values (56,"diapers wipes");
insert into aisle values (57,"granola");
insert into aisle values (58,"frozen breads doughs");
insert into aisle values (59,"canned meals beans");
insert into aisle values (60,"trash bags liners");
insert into aisle values (61,"cookies cakes");
insert into aisle values (62,"white wines");
insert into aisle values (63,"grains rice dried goods");
insert into aisle values (64,"energy sports drinks");
insert into aisle values (65,"protein meal replacements");
insert into aisle values (66,"asian foods");
insert into aisle values (67,"fresh dips tapenades");
insert into aisle values (68,"bulk grains rice dried goods");
insert into aisle values (69,"soup broth bouillon");
insert into aisle values (70,"digestion");
insert into aisle values (71,"refrigerated pudding desserts");
insert into aisle values (72,"condiments");
insert into aisle values (73,"facial care");
insert into aisle values (74,"dish detergents");
insert into aisle values (75,"laundry");
insert into aisle values (76,"indian foods");
insert into aisle values (77,"soft drinks");
insert into aisle values (78,"crackers");
insert into aisle values (79,"frozen pizza");
insert into aisle values (80,"deodorants");
insert into aisle values (81,"canned jarred vegetables");
insert into aisle values (82,"baby accessories");
insert into aisle values (83,"fresh vegetables");
insert into aisle values (84,"milk");
insert into aisle values (85,"food storage");
insert into aisle values (86,"eggs");
insert into aisle values (87,"more household");
insert into aisle values (88,"spreads");
insert into aisle values (89,"salad dressing toppings");
insert into aisle values (90,"cocoa drink mixes");
insert into aisle values (91,"soy lactosefree");
insert into aisle values (92,"baby food formula");
insert into aisle values (93,"breakfast bakery");
insert into aisle values (94,"tea");
insert into aisle values (95,"canned meat seafood");
insert into aisle values (96,"lunch meat");
insert into aisle values (97,"baking supplies decor");
insert into aisle values (98,"juice nectars");
insert into aisle values (99,"canned fruit applesauce");
insert into aisle values (100,"missing");
insert into aisle values (101,"air fresheners candles");
insert into aisle values (102,"baby bath body care");
insert into aisle values (103,"ice cream toppings");
insert into aisle values (104,"spices seasonings");
insert into aisle values (105,"doughs gelatins bake mixes");
insert into aisle values (106,"hot dogs bacon sausage");
insert into aisle values (107,"chips pretzels");
insert into aisle values (108,"other creams cheeses");
insert into aisle values (109,"skin care");
insert into aisle values (110,"pickled goods olives");
insert into aisle values (111,"plates bowls cups flatware");
insert into aisle values (112,"bread");
insert into aisle values (113,"frozen juice");
insert into aisle values (114,"cleaning products");
insert into aisle values (115,"water seltzer sparkling water");
insert into aisle values (116,"frozen produce");
insert into aisle values (117,"nuts seeds dried fruit");
insert into aisle values (118,"first aid");
insert into aisle values (119,"frozen dessert");
insert into aisle values (120,"yogurt");
insert into aisle values (121,"cereal");
insert into aisle values (122,"meat counter");
insert into aisle values (123,"packaged vegetables fruits");
insert into aisle values (124,"spirits");
insert into aisle values (125,"trail mix snack mix");
insert into aisle values (126,"feminine care");
insert into aisle values (127,"body lotions soap");
insert into aisle values (128,"tortillas flat bread");
insert into aisle values (129,"frozen appetizers sides");
insert into aisle values (130,"hot cereal pancake mixes");
insert into aisle values (131,"dry pasta");
insert into aisle values (132,"beauty");
insert into aisle values (133,"muscles joints pain relief");
insert into aisle values (134,"specialty wines champagnes");
